[package]
name = "cve_2022_1388_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
colored = "2"
reqwest = {version = "0.11.10", features = ["json"]} 
tokio = { version = "1", features = ["full"] }
url = "2.2.2"
snailquote = "0.3.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"